# User config
author: "Pineapple"
tagline: "Pineapple Certfied Jekyll Theme"
description: "Hello! Welcome to My Blog."
email: "yychen8010@gmail.com"
linkedin: "https://www.linkedin.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
