# User config
author: "Rita"
tagline: "My Blog"
description: "Hello! Welcome to my blog, where I share my journey in landscape architecture. I'm passionate about creating sustainable, vibrant spaces for living, playing, and working, using design to meaningfully connect people with their environment."
email: "yychen8010@gmail.com"
linkedin: "https://www.linkedin.com/in/rita-chen-56b5ab169/"

# Site config
baseurl: ""
url: "https://geasssoul.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
