# User config
author: "HOME"
tagline: "Pineapple Certfied Jekyll Theme"
description: "Hello! Welcome to My Blog."
email: "yychen8010@gmail.com"
linkedin: "https://www.linkedin.com/in/rita-chen-56b5ab169/"

# Site config
baseurl: ""
url: "https://geasssoul.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
